<?php

/*
--------------------------------------------------------------------------------------------------
Register our ACF fields for the Show Me the Wheels module
--------------------------------------------------------------------------------------------------
*/ 

if( function_exists('acf_add_local_field_group') ):

// SMTW's custom post type acf fields
// ------------------------------------------------------
acf_add_local_field_group(array (
	'key' => 'group_5787b50b85070',
	'title' => 'SMTW\'s Entry Fields',
	'fields' => array (
		array (
			'key' => 'field_57890f495041b',
			'label' => 'Personal Details',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'left',
			'endpoint' => 0,
		),
		array (
			'key' => 'field_5787b51f5c20e',
			'label' => 'First Name',
			'name' => 'smtw_firstname',
			'type' => 'text',
			'instructions' => 'First Name of Participant',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_57890ef150418',
			'label' => 'Last Name',
			'name' => 'smtw_lastname',
			'type' => 'text',
			'instructions' => 'Last Name of Participant',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_57890f0a50419',
			'label' => 'Facebook ID',
			'name' => 'smtw_facebookid',
			'type' => 'text',
			'instructions' => 'Facebook ID of Participant',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_57890f315041a',
			'label' => 'Email Address',
			'name' => 'smtw_email',
			'type' => 'text',
			'instructions' => 'Email Address of Participant',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_57890f655041c',
			'label' => 'Image',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'left',
			'endpoint' => 0,
		),
		array (
			'key' => 'field_57890d4f50417',
			'label' => 'Image',
			'name' => 'smtw_image',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'preview_size' => 'thumbnail',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'showmethewheels',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'acf_after_title',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

// SMTW's acf options fields
// ------------------------------------------------------
acf_add_local_field_group(array (
	'key' => 'group_5790ca534779f',
	'title' => 'SMTW\'s settings',
	'fields' => array (
		array (
			'key' => 'field_5790ca73bc455',
			'label' => 'MailChimp API Key',
			'name' => 'smtw_mc_api_key',
			'type' => 'text',
			'instructions' => 'Add a MailChimp API key, if left blank the form will not submit entries to MailChimp',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_5790caa5bc456',
			'label' => 'MailChimp List ID',
			'name' => 'smtw_mc_list_id',
			'type' => 'text',
			'instructions' => 'Add a MailChimp list ID to add submitted data to, if left blank the form will not submit entries to MailChimp',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
	array (
			'key' => 'field_5799de1c0025b',
			'label' => 'SMTW Legal',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array (
			'key' => 'field_5799de2c0025c',
			'label' => 'Terms & Conditions Text',
			'name' => 'smtw_terms_&_conditions',
			'type' => 'textarea',
			'instructions' => 'Set the Show Me The Wheels terms and conditions text',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => 'wpautop',
			'readonly' => 0,
			'disabled' => 0,
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'acf-options-smtw-settings',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'left',
	'instruction_placement' => 'label',
	'hide_on_screen' => array (
		0 => 'permalink',
		1 => 'the_content',
		2 => 'excerpt',
		3 => 'custom_fields',
		4 => 'discussion',
		5 => 'comments',
		6 => 'revisions',
		7 => 'slug',
		8 => 'author',
		9 => 'format',
		10 => 'page_attributes',
		11 => 'featured_image',
		12 => 'categories',
		13 => 'tags',
		14 => 'send-trackbacks',
	),
	'active' => 1,
	'description' => 'SMTW\'s settings',
));

endif;


?>